// src/components/Navbar.js (or Navbar.tsx)

import Link from 'next/link'; // Next.js Link component for client-side navigation
import styles from './Navbar.module.css'; // Import the CSS Module

/**
 * Navbar component for the application.
 * This component displays the main navigation links.
 * It is styled using a CSS Module (Navbar.module.css).
 */
export default function Navbar() {
  return (
    // Assign CSS classes from the imported 'styles' object.
    // styles.navbar will be a unique class name generated by Next.js/Webpack.
    <nav className={styles.navbar}>
      {/* Logo or Site Title - "Book Haven" */}
      <div className={styles.logo}>
        {/* Link to the homepage */}
        <Link href="/" className={styles.navLinksA}> {/* Using a common class for hover effect */}
          Book Haven
        </Link>
      </div>

      {/* Navigation Links - Home, AboutUs, Book, Category, Contact */}
      <ul className={styles.navLinks}>
        <li>
          {/* Each Link component handles navigation to a specific route. */}
          <Link href="/" className={styles.navLinksA}>
            Home
          </Link>
        </li>
        <li>
          <Link href="/aboutus" className={styles.navLinksA}>
            AboutUs
          </Link>
        </li>
        <li>
          <Link href="/book" className={styles.navLinksA}>
            Book
          </Link>
        </li>
        <li>
          <Link href="/category" className={styles.navLinksA}>
            Category
          </Link>
        </li>
        <li>
          <Link href="/contact" className={styles.navLinksA}>
            Contact
          </Link>
        </li>
      </ul>
    </nav>
  );
}
