// src/app/layout.tsx
import './globals.css';

import React from 'react'; // <--- Ensure React is imported for typing

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

// Define the type for the props of RootLayout
interface RootLayoutProps {
  children: React.ReactNode;
}

// Use the defined interface for your component's props
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}