

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}

// Optional: Add metadata for SEO. This is often present in new Next.js projects.
export const metadata = {
  title: 'Create Next App', // You can change this
  description: 'Generated by create next app', // You can change this
};